[package]
name = "next_hit"
version = "0.1.0"
edition = "2021"
authors = ["Yang Chen <matthiasychen@gmail.com>"]

[dependencies]
embree = { path = "../.." }
support = { path = "../support" }
glam = "0.23.0"
